stages:
  - build
  - test
  - coverage
  - deploy

image: maven:3.6.1-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.test.failure.ignore=true"

build:
  stage: build
  script:
    - mvn install -DskipTests

test_helpertools:
  stage: test
  script:
    - cd core/helper-tools/
    - pwd
    - mvn test
  artifacts:
    reports:
      junit:
        - /builds/nanosat-mo-framework/nanosat-mo-framework/core/helper-tools/target/surefire-reports/TEST-*.xml

cover_helpertools:
  stage: coverage
  script:
    - cd core/helper-tools/
    - mvn $MAVEN_OPTS test
  artifacts:
    paths:
      - /builds/nanosat-mo-framework/nanosat-mo-framework/core/helper-tools/target/site/jacoco/
