stages:
  - build
  - test
  - deploy

image: maven:3.3.9-jdk-8

build:
  stage: build
  script:
    - mvn install -DskipTests

test_helpertools:
  stage: test
  script:
    - cd core/helper-tools/
    - mvn test
  artifacts:
    reports:
      junit:
        - /builds/nanosat-mo-framework/nanosat-mo-framework/core/helper-tools/target/surefire-reports/TEST-*.xml
    paths:
      - /builds/nanosat-mo-framework/nanosat-mo-framework/core/helper-tools/target/surefire-reports/TEST-*.xml

cover_helpertools:
  stage: test
  script:
    - cd core/helper-tools/
    - mvn -Dmaven.test.failure.ignore=true test
  artifacts:
    paths:
      - /builds/nanosat-mo-framework/nanosat-mo-framework/core/helper-tools/target/site/jacoco/
